FROM python:3.9

RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc ffmpeg libsm6 libxext6 libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev && \
    apt clean && rm -rf /var/lib/apt/lists/*
COPY ./requirements.txt /requirements.txt
COPY ./src /src

RUN pip3 install --no-cache-dir -r /requirements.txt
CMD ["python3", "/src/test2.py"]
