FROM python:3.9-slim

RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc ffmpeg libsm6 libxext6 && \
    apt clean && rm -rf /var/lib/apt/lists/*
COPY ./requirements.txt /requirements.txt
COPY ./src /src

RUN pip3 install --no-cache-dir -r /requirements.txt
CMD ["python3", "/ui-app/src/app.py"]
EXPOSE 5001
